cake = DessertType.create(name:"CAKE") 
ice_cream = DessertType.create(name:"ICE-CREAM") 
choco = DessertType.create(name:"CHOCOLATES") 

Dessert.create(name:"BLACK-FOREST", dessert_type: cake)
Dessert.create(name:"Angel cake", dessert_type: cake)
Dessert.create(name:"Apple cake", dessert_type: cake)
Dessert.create(name:"Babka cake", dessert_type: cake)
Dessert.create(name:"Cheesecake", dessert_type: cake)
Dessert.create(name:"Grape ice cream", dessert_type: ice_cream)
Dessert.create(name:"Halva ice cream", dessert_type: ice_cream)
Dessert.create(name:"Black and Tan", dessert_type: ice_cream)
Dessert.create(name:"Chocolate ice cream", dessert_type: ice_cream)
Dessert.create(name:"Cookies and Cream", dessert_type: ice_cream)
Dessert.create(name:"Banana Chocolate", dessert_type:  choco)
Dessert.create(name:"Black Pearl Bar", dessert_type:  choco)
Dessert.create(name:" Lavender truffles", dessert_type:  choco)
Dessert.create(name:"Naga Bar", dessert_type:  choco)
Dessert.create(name:"Mo’s Bacon Bar", dessert_type:  choco)
